version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: parcial_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  create:
    build: ./services/create
    container_name: create_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - CREATE_PORT=${CREATE_PORT}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "${CREATE_PORT}:${CREATE_PORT}"

  read:
    build: ./services/read
    container_name: read_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - READ_PORT=${READ_PORT}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "${READ_PORT}:${READ_PORT}"

  update:
    build: ./services/update
    container_name: update_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - UPDATE_PORT=${UPDATE_PORT}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "${UPDATE_PORT}:${UPDATE_PORT}"

  delete:
    build: ./services/delete
    container_name: delete_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - DELETE_PORT=${DELETE_PORT}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "${DELETE_PORT}:${DELETE_PORT}"

volumes:
  mongo_data:
